import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, EnvelopeSimple, GithubLogo, LinkedinLogo, ShoppingCartSimple, Spade, X, List } from "@phosphor-icons/react";
import { studies, pathForStudy, getStudy } from "./case-studies.js";
import { CasePage } from "./CasePage.jsx";
import { ScrollStory } from "./ScrollStory.jsx";

const email = "tyagi.shubham177@gmail.com";
const linkedin = "https://www.linkedin.com/in/tyagishubham2803/";
const github = "https://github.com/tyagishubham177";
const projects = [{name:"PolyCart",description:"Exploring commerce architecture, service boundaries and resilient workflows.",href:`${github}/PolyCart`,icon:ShoppingCartSimple},{name:"PokerPreflopStrategy",description:"A tool for practising preflop decisions and learning by playing.",href:`${github}/PokerPreflopStrategy`,icon:Spade}];

function Label({children}) { return <p className="section-label">{children}<span aria-hidden="true" /></p>; }
function Header({path}) {
  const [open,setOpen] = useState(false);
  useEffect(()=>{const close=e=>{if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="site-header__inner">
    <a className="wordmark" href="/">Shubham Tyagi</a><nav id="primary-nav" aria-label="Primary navigation" className={open?"nav nav--open":"nav"}>
      {[['Work','/work/'],['Build Lab','/build-lab/'],['About','/about/'],['Contact','/#contact']].map(([label,href])=><a key={label} href={href} aria-current={path===href?'page':undefined}>{label}</a>)}
    </nav><a className="button button--header" href={`mailto:${email}`}>Let’s talk <ArrowUpRight size={16} aria-hidden="true" /></a>
    <button className="menu-button" aria-controls="primary-nav" aria-expanded={open} aria-label={open?'Close menu':'Open menu'} type="button" onClick={()=>setOpen(!open)}>{open?<X size={25} aria-hidden="true"/>:<List size={25} aria-hidden="true"/>}</button>
  </div></header></>;
}
function Footer(){return <footer className="footer page-shell"><span>© {new Date().getFullYear()} Shubham Tyagi</span><span>Built with curiosity and care.</span><a href="#top">Back to top</a></footer>}
function CaseCard({study}){return <article className="case-card reveal"><img className="case-card__image" src={study.image} alt={study.imageAlt} loading="lazy"/><div className="case-card__body"><h3>{study.shortTitle}</h3><p className="eyebrow case-card__label">{study.category}</p><p>{study.description}</p><a className="text-link" href={pathForStudy(study)}>Explore case <ArrowRight size={19} aria-hidden="true"/></a></div></article>}
function BuildProject({project}){const Icon=project.icon;return <a className="build-project" href={project.href} target="_blank" rel="noopener noreferrer"><span className="build-project__icon"><Icon size={27} aria-hidden="true"/></span><span className="build-project__copy"><strong>{project.name}</strong><span>{project.description}</span></span><ArrowUpRight className="build-project__arrow" size={22} aria-hidden="true"/></a>}
function Contact(){return <section className="contact page-shell reveal" id="contact"><Label>Let’s connect</Label><h2>Have a complex problem worth untangling?</h2><p>I’d love to talk about product roles, healthcare technology, enterprise workflows or a useful idea you’re building.</p><div className="contact__links"><a className="button" href={`mailto:${email}`}><EnvelopeSimple size={21} aria-hidden="true"/> Email me</a><a className="contact__social" href={linkedin} target="_blank" rel="noopener noreferrer"><LinkedinLogo size={21} aria-hidden="true"/> LinkedIn</a><a className="contact__social" href={github} target="_blank" rel="noopener noreferrer"><GithubLogo size={21} aria-hidden="true"/> GitHub</a></div></section>}
function Home(){return <main id="main">
  <section className="hero page-shell" id="top"><div className="hero__copy"><Label>Product · People · Progress</Label><h1>Hi, I’m Shubham<span className="period">.</span><br/>I make complex products easier to use<span className="period">.</span></h1><p className="hero__role">From technical leadership to product management</p><p className="hero__summary">I connect customer problems, technical constraints, and the teams that turn ideas into working products.</p><div className="hero__actions"><a className="button" href="/work/">See my work <ArrowRight size={21} aria-hidden="true"/></a><a className="underlined-link" href="/about/">More about me</a></div></div><img className="hero__illustration" src="/assets/hero-illustration.png" alt="Hand-drawn notes about curiosity, people, ideas, technology and impact"/></section>
  <section className="featured page-shell" id="work" aria-label="Featured work"><div className="featured__main"><Label>Featured work</Label><div className="case-grid">{studies.slice(0,2).map(study=><CaseCard study={study} key={study.slug}/>)}</div><div className="home-more"><span>Also: a diabetes companion built around useful engagement.</span><a className="text-link" href="/work/diabetes-companion/">Explore case 03 <ArrowRight size={17} aria-hidden="true"/></a></div></div><aside className="featured__aside" id="build-lab"><Label>Build Lab</Label>{projects.map(project=><BuildProject key={project.name} project={project}/>)}<a className="all-projects-link" href="/build-lab/">Inside the Build Lab <ArrowRight size={17} aria-hidden="true"/></a></aside></section>
  <ScrollStory/>
  <section className="home-about page-shell reveal"><div><Label>About me</Label><h2>I like the space where people, systems, and decisions meet.</h2></div><div><p>My background spans software engineering and technical leadership in healthcare and enterprise products. I’m bringing that experience into product management.</p><p>I’m pursuing the IPMX Executive MBA at IIM Lucknow.</p><a className="text-link" href="/about/">The longer story <ArrowRight size={20} aria-hidden="true"/></a></div></section><Contact/>
</main>}
function Work(){return <main id="main" className="work-index page-shell"><div id="top"><Label>Selected product work</Label><h1>Complex workflows.<br/>Human consequences.</h1><p className="index-deck">Three healthcare product stories: the context, the contribution, the trade-off—and the evidence still needed.</p></div>{studies.map(study=><a className="work-row reveal" key={study.slug} href={pathForStudy(study)}><span className="work-row__number">{study.number}</span><div><h2>{study.shortTitle}</h2><p className="eyebrow">{study.category}</p></div><p className="work-row__description">{study.description}</p><ArrowUpRight size={28} aria-hidden="true"/></a>)}</main>}
function About(){return <main id="main" className="standalone-page page-shell"><div id="top"><Label>About me</Label><h1>Technical depth.<br/>A product-minded next chapter.</h1><p className="index-deck">I’m Shubham Tyagi—an engineer and technical leader moving towards product management, with a particular interest in healthcare and complex enterprise workflows.</p></div><section className="standalone-grid reveal"><h2>Close to the work.<br/>Curious about the why.</h2><div><p>My experience includes Technical Lead work at HCLTech and engineering roles across healthcare and enterprise products. The product-facing thread is understanding the workflow, translating user and stakeholder needs, and making technical constraints visible.</p><p>I do not replace those formal roles with a PM title. My case studies separate what I contributed, what the source account supports, and what still needs stronger evidence.</p><p>I’m pursuing the IPMX Executive MBA at IIM Lucknow, bringing management study together with practical experience of building and delivering software.</p></div></section><section className="standalone-grid reveal"><h2>What I want to work on.</h2><div><p>Products where clarity changes the quality of a decision: healthcare information flows, reusable enterprise platforms and useful AI assistance with visible human judgment.</p><p>My current AI document-triage exploration is a concept and validation plan. It is not presented as a launched product or an achieved outcome.</p><a className="text-link" href="/work/">Read the product stories <ArrowRight size={20} aria-hidden="true"/></a></div></section><a className="button" href={linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <ArrowUpRight size={20} aria-hidden="true"/></a></main>}
function Lab(){return <main id="main" className="standalone-page page-shell"><div id="top"><Label>Build Lab</Label><h1>Thinking becomes clearer<br/>when you build something.</h1><p className="index-deck">A small collection of public code projects. These are side projects, distinct from the employer product case studies.</p></div><div className="lab-grid">{projects.map(project=>{const Icon=project.icon;return <article className="lab-entry reveal" key={project.name}><Icon size={42} color="#c94031" aria-hidden="true"/><h2>{project.name}</h2><p>{project.description}</p><a className="text-link" href={project.href} target="_blank" rel="noopener noreferrer">Explore repository <ArrowUpRight size={20} aria-hidden="true"/></a></article>})}</div><section className="standalone-grid reveal"><h2>AI document triage.<br/>An open product question.</h2><div><p>I’m exploring how operations teams might review and route documents using AI assistance while preserving exceptions, human judgment and auditability.</p><p>Current stage: concept and validation plan. The next step is to establish the user workflow and a testable value proposition—not to claim automation savings before a pilot.</p></div></section><a className="text-link" href={github} target="_blank" rel="noopener noreferrer">More on GitHub <ArrowUpRight size={19} aria-hidden="true"/></a></main>}
function NotFound(){return <main className="standalone-page page-shell" id="main"><div id="top"><Label>404 / Not found</Label><h1>This page isn’t here.</h1><p className="index-deck">You can find the product stories in the work collection.</p><a className="button" href="/work/">Explore the work <ArrowRight size={20} aria-hidden="true"/></a></div></main>}

export function App({path="/"}) {
  useEffect(()=>{
    if(!('IntersectionObserver' in window))return;
    const items=[...document.querySelectorAll('.reveal')];
    items.forEach(item=>{if(item.getBoundingClientRect().top>innerHeight)item.classList.add('is-pending')});
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('is-pending');entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.06});
    items.forEach(item=>observer.observe(item));return()=>observer.disconnect();
  },[path]);
  const study=getStudy(path);
  const page=study?<CasePage study={study}/>:path==='/'?<Home/>:path==='/work/'?<Work/>:path==='/about/'?<About/>:path==='/build-lab/'?<Lab/>:<NotFound/>;
  return <><Header path={path}/>{page}<Footer/></>;
}
