import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, EnvelopeSimple, GithubLogo, LinkedinLogo, ShoppingCartSimple, Spade, X, List } from "@phosphor-icons/react";
import { studies, pathForStudy, getStudy } from "./case-studies.js";
import { CasePage } from "./CasePage.jsx";
import { ScrollStory } from "./ScrollStory.jsx";
import { ProductSculpture, SculptureMotionProvider, useSculptureMotion } from "./ProductSculpture.jsx";
import "./sculptural-layouts.css";

const email = "tyagi.shubham177@gmail.com";
const linkedin = "https://www.linkedin.com/in/tyagishubham2803/";
const github = "https://github.com/tyagishubham177";
const projects = [{name:"PolyCart",description:"Exploring commerce architecture, service boundaries and resilient workflows.",href:`${github}/PolyCart`,icon:ShoppingCartSimple},{name:"PokerPreflopStrategy",description:"A tool for practising preflop decisions and learning by playing.",href:`${github}/PokerPreflopStrategy`,icon:Spade}];

function Label({children}) { return <p className="section-label">{children}<span aria-hidden="true" /></p>; }
function Header({path}) {
  const [open,setOpen] = useState(false);
  useEffect(()=>{const close=e=>{if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="site-header__inner">
    <a className="wordmark" href="/">Shubham Tyagi</a><nav id="primary-nav" aria-label="Primary navigation" className={open?"nav nav--open":"nav"}>
      {[['Work','/work/'],['Build Lab','/build-lab/'],['About','/about/'],['Contact','/#contact']].map(([label,href])=><a key={label} href={href} aria-current={path===href?'page':undefined}>{label}</a>)}
    </nav><a className="button button--header" href={`mailto:${email}`}>Let’s talk <ArrowUpRight size={16} aria-hidden="true" /></a>
    <button className="menu-button" aria-controls="primary-nav" aria-expanded={open} aria-label={open?'Close menu':'Open menu'} type="button" onClick={()=>setOpen(!open)}>{open?<X size={25} aria-hidden="true"/>:<List size={25} aria-hidden="true"/>}</button>
  </div></header></>;
}
function Footer(){return <footer className="footer page-shell"><span>© {new Date().getFullYear()} Shubham Tyagi</span><span>Built with curiosity and care.</span><a href="#top">Back to top</a></footer>}
const visualFor=study=>study.slug==='hospital-digitalisation'?'hospital':study.slug==='vascular-access'?'platform':'engagement';
const visualWords={hospital:['Capture','Review','Use'],platform:['One core','Local needs','Shared control'],engagement:['Utility','Feedback','Return']};
function CaseCard({study}){const variant=visualFor(study);return <article className={`project-feature project-feature--${variant} reveal`}>
  <a className="project-feature__visual" href={pathForStudy(study)} aria-label={`Explore ${study.shortTitle}`}><ProductSculpture variant={variant}/><span className="project-feature__visual-foot"><span>{study.number} / Conceptual study</span><ArrowUpRight size={26} aria-hidden="true"/></span></a>
  <div className="project-feature__copy"><p className="section-label">{study.number} / {study.category}</p><h3>{study.shortTitle}</h3><p>{study.description}</p><div className="visual-words" aria-label="Product themes">{visualWords[variant].map(word=><span key={word}>{word}</span>)}</div><a className="text-link" href={pathForStudy(study)}>Inside the case <ArrowRight size={20} aria-hidden="true"/></a></div>
</article>}
function BuildProject({project}){const Icon=project.icon;return <a className="build-project" href={project.href} target="_blank" rel="noopener noreferrer"><span className="build-project__icon"><Icon size={27} aria-hidden="true"/></span><span className="build-project__copy"><strong>{project.name}</strong><span>{project.description}</span></span><ArrowUpRight className="build-project__arrow" size={22} aria-hidden="true"/></a>}
function Contact(){return <section className="contact page-shell reveal" id="contact"><Label>Let’s connect</Label><h2>Have a complex problem worth untangling?</h2><p>I’d love to talk about product roles, healthcare technology, enterprise workflows or a useful idea you’re building.</p><div className="contact__links"><a className="button" href={`mailto:${email}`}><EnvelopeSimple size={21} aria-hidden="true"/> Email me</a><a className="contact__social" href={linkedin} target="_blank" rel="noopener noreferrer"><LinkedinLogo size={21} aria-hidden="true"/> LinkedIn</a><a className="contact__social" href={github} target="_blank" rel="noopener noreferrer"><GithubLogo size={21} aria-hidden="true"/> GitHub</a></div></section>}
function Home(){return <main id="main">
  <section className="hero sculptural-hero" id="top"><div className="hero__copy"><Label>Product · People · Progress</Label><h1>Hi, I’m Shubham<span className="period">.</span><br/>I make complex products easier to use<span className="period">.</span></h1><p className="hero__role">From technical leadership to product management</p><p className="hero__summary">I connect customer problems, technical constraints, and the teams that turn ideas into working products.</p><div className="hero__actions"><a className="button" href="/work/">See my work <ArrowRight size={21} aria-hidden="true"/></a><a className="underlined-link" href="/about/">More about me</a></div></div><div className="hero-object"><ProductSculpture variant="hero"/><div className="hero-object__caption"><span>People</span><span>Systems</span><span>Possibility</span></div></div></section>
  <section className="sculptural-featured page-shell" id="work" aria-label="Featured work"><div className="work-heading"><Label>Featured work</Label><p>Different products.<br/><span>The same curiosity.</span></p><a className="text-link" href="/work/">All product work <ArrowRight size={20} aria-hidden="true"/></a></div>{studies.map(study=><CaseCard study={study} key={study.slug}/>)}</section>
  <section className="home-lab-strip page-shell" id="build-lab"><div><Label>Build Lab</Label><h2>Side quests.<br/>Real code.</h2><a className="text-link" href="/build-lab/">Inside the Build Lab <ArrowRight size={20} aria-hidden="true"/></a></div><div>{projects.map(project=><BuildProject key={project.name} project={project}/>)}</div></section>
  <ScrollStory/>
  <section className="home-about page-shell reveal"><div><Label>About me</Label><h2>I like the space where people, systems, and decisions meet.</h2></div><div><p>My background spans software engineering and technical leadership in healthcare and enterprise products. I’m bringing that experience into product management.</p><p>I’m pursuing the IPMX Executive MBA at IIM Lucknow.</p><a className="text-link" href="/about/">The longer story <ArrowRight size={20} aria-hidden="true"/></a></div></section><Contact/>
</main>}
function Work(){return <main id="main" className="work-index page-shell"><div id="top"><Label>Selected product work</Label><h1>Complex workflows.<br/>Human consequences.</h1><p className="index-deck">Three healthcare product stories: the context, the contribution, the trade-off—and the evidence still needed.</p></div>{studies.map(study=><CaseCard study={study} key={study.slug}/>)}</main>}
function About(){return <main id="main" className="standalone-page page-shell"><div id="top"><Label>About me</Label><h1>Technical depth.<br/>A product-minded next chapter.</h1><p className="index-deck">I’m Shubham Tyagi—an engineer and technical leader moving towards product management, with a particular interest in healthcare and complex enterprise workflows.</p></div><section className="standalone-grid reveal"><h2>Close to the work.<br/>Curious about the why.</h2><div><p>My experience includes Technical Lead work at HCLTech and engineering roles across healthcare and enterprise products. The product-facing thread is understanding the workflow, translating user and stakeholder needs, and making technical constraints visible.</p><p>I do not replace those formal roles with a PM title. My case studies separate what I contributed, what the source account supports, and what still needs stronger evidence.</p><p>I’m pursuing the IPMX Executive MBA at IIM Lucknow, bringing management study together with practical experience of building and delivering software.</p></div></section><section className="standalone-grid reveal"><h2>What I want to work on.</h2><div><p>Products where clarity changes the quality of a decision: healthcare information flows, reusable enterprise platforms and useful AI assistance with visible human judgment.</p><p>My current AI document-triage exploration is a concept and validation plan. It is not presented as a launched product or an achieved outcome.</p><a className="text-link" href="/work/">Read the product stories <ArrowRight size={20} aria-hidden="true"/></a></div></section><a className="button" href={linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <ArrowUpRight size={20} aria-hidden="true"/></a></main>}
function Lab(){return <main id="main" className="standalone-page page-shell"><div id="top"><Label>Build Lab</Label><h1>Thinking becomes clearer<br/>when you build something.</h1><p className="index-deck">A small collection of public code projects. These are side projects, distinct from the employer product case studies.</p></div><div className="lab-grid">{projects.map(project=>{const Icon=project.icon;return <article className="lab-entry reveal" key={project.name}><Icon size={42} color="#c94031" aria-hidden="true"/><h2>{project.name}</h2><p>{project.description}</p><a className="text-link" href={project.href} target="_blank" rel="noopener noreferrer">Explore repository <ArrowUpRight size={20} aria-hidden="true"/></a></article>})}</div><section className="standalone-grid reveal"><h2>AI document triage.<br/>An open product question.</h2><div><p>I’m exploring how operations teams might review and route documents using AI assistance while preserving exceptions, human judgment and auditability.</p><p>Current stage: concept and validation plan. The next step is to establish the user workflow and a testable value proposition—not to claim automation savings before a pilot.</p></div></section><a className="text-link" href={github} target="_blank" rel="noopener noreferrer">More on GitHub <ArrowUpRight size={19} aria-hidden="true"/></a></main>}
function NotFound(){return <main className="standalone-page page-shell" id="main"><div id="top"><Label>404 / Not found</Label><h1>This page isn’t here.</h1><p className="index-deck">You can find the product stories in the work collection.</p><a className="button" href="/work/">Explore the work <ArrowRight size={20} aria-hidden="true"/></a></div></main>}

function MotionControl(){const {enabled,toggle,reducedMotion}=useSculptureMotion();useEffect(()=>{document.documentElement.dataset.motionState=enabled&&!reducedMotion?'on':'off'},[enabled,reducedMotion]);return <button className="global-motion" type="button" aria-label={reducedMotion?'Reduced motion preference active':enabled?'Turn all motion off':'Turn all motion on'} aria-pressed={enabled&&!reducedMotion} disabled={reducedMotion} onClick={toggle}><span aria-hidden="true" className="global-motion__dot"/>{reducedMotion?'Reduced motion':enabled?'Motion on':'Motion off'}</button>}
function Portfolio({path="/"}) {
  useEffect(()=>{
    if(!('IntersectionObserver' in window))return;
    const items=[...document.querySelectorAll('.reveal')];
    items.forEach(item=>{if(item.getBoundingClientRect().top>innerHeight)item.classList.add('is-pending')});
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('is-pending');entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.06});
    items.forEach(item=>observer.observe(item));return()=>observer.disconnect();
  },[path]);
  const study=getStudy(path);
  const page=study?<CasePage study={study}/>:path==='/'?<Home/>:path==='/work/'?<Work/>:path==='/about/'?<About/>:path==='/build-lab/'?<Lab/>:<NotFound/>;
  return <><Header path={path}/>{page}<Footer/><MotionControl/></>;
}
export function App({path="/"}){return <SculptureMotionProvider><Portfolio path={path}/></SculptureMotionProvider>}
